# MCP (Model Context Protocol) servers
# Usage: docker-compose -f docker-compose.core.yml -f docker-compose.mcp.yml up

version: "3.9"

networks:
  youworker-network:
    external: true

services:
  # MCP Web server (search, fetch, crawl)
  mcp_web:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.mcp_web
    container_name: youworker-mcp-web
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=7001
    ports:
      - "${MCP_WEB_PORT:-7001}:7001"
    networks:
      - youworker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Semantic search server
  mcp_semantic:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.mcp_semantic
    container_name: youworker-mcp-semantic
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
    environment:
      - HOST=0.0.0.0
      - PORT=7002
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
    ports:
      - "${MCP_SEMANTIC_PORT:-7002}:7002"
    networks:
      - youworker-network

  # MCP Datetime server
  mcp_datetime:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.mcp_datetime
    container_name: youworker-mcp-datetime
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=7003
    ports:
      - "${MCP_DATETIME_PORT:-7003}:7003"
    networks:
      - youworker-network

  # MCP Ingestion server
  mcp_ingest:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.mcp_ingest
    container_name: youworker-mcp-ingest
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
      - postgres
    environment:
      - HOST=0.0.0.0
      - PORT=7004
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-youworker}
    volumes:
      - uploads:/data/uploads
      - ../../examples:/data/examples:ro
    ports:
      - "${MCP_INGEST_PORT:-7004}:7004"
    networks:
      - youworker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # MCP Units conversion server
  mcp_units:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.mcp_units
    container_name: youworker-mcp-units
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=7005
    ports:
      - "${MCP_UNITS_PORT:-7005}:7005"
    networks:
      - youworker-network

volumes:
  uploads:
    external: true
