import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import PageHeader from "./components/PageHeader";
import { AuthProvider } from "../contexts/AuthContext";

export const metadata: Metadata = {
  title: "YouWorker.ai",
  description: "Generated by Next.js 16",
  icons: {
    icon: "/YouWorker.ai-ico.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <div className="page-container">
            <PageHeader />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
